### PR TITLE
Adds offset support for LinearRegressor, LogisticRegressor, LinearCountRegressor

### PR DESCRIPTION
**Pull request by olivierlabayle**
In the interest of time, I decided to take the short way. Hope this also matches what you had in mind.

I'm wondering to what extent it would be worth implementing the `reformat` method instead of  my `prepare_inputs`? With a return output like `X, y = (Xmatrix, offset), y`? I guess this would mean quite many changes to the tests and code but may be worth for performance? Let me know your thougths.

### CODE REVIEW

**Comment by olivierlabayle** [comment]
@ablaom I guess you are quite busy these days, may I catch your attention here?

**Review by ablaom — APPROVED** [review]
Thanks for the reminder. This had indeed fallen off my radar for the present. 

Looks good to me. 

The imperative for introducing the `reformat` apparatus was to speed up iterative models, which, according to the mechanisms in `IterationControl` were otherwise converting data every iteration. However, there is also a performance benefit for hyper-parameter tuning whenever using any strategy except `Holdout` (which didn't force the reconversion). So definitely worth doing. Happy to review (more promptly) if you wish to proceed with that.

**Comment by ablaom** [comment]
But as implementing `reformat`/`selectrows` is purely an implementation change, you could, of course, make this a separate PR if you're keen to get the new functionality ASAP.

**Comment by olivierlabayle** [comment]
Yes, I don't have much time at the moment so its probably preferable to review it as is. We can track the ```reformat/selectrows``` in a separate issue that I'll be happy to take later on.

**Pull request merged**
